config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root :controller => :register, :action => :index

  get '/register/success', to: 'register#success'
  get '/register/:step', to: 'register#show'
  post '/register/:step', to: 'register#create', as: 'register_step'

  get '/register', to: redirect('/register/1')

  resources :registrations, only: [:show, :index, :create]

  namespace :admin do
    root to: redirect('/admin/pupils?semester=current')
    post '/pupils/command' => 'pupils#command'
    post '/companies/command' => 'companies#command'
    post '/schools/command' => 'schools#command'
    post '/semesters/command' => 'school_semesters#command'
    post '/school_class_types/command' => 'school_class_types#command'
    post '/users/command' => 'users#command'
    resource :charts do
      get 'weekly'
    end

    resources :pupils, only: [:new, :create, :show, :destroy, :index, :update] do
      get :checkin, path: 'checkin', to: 'pupils#checkin'
      post :checkin, path: 'checkin', to: 'pupils#do_checkin'
      get :delete_photo, path: 'delete_photo', to: 'pupils#delete_photo'
      get :invoice, path: 'invoice', to: 'pupils#invoice'
      resources :comments, controller: 'pupil_comments' do
        get :delete, to: 'pupil_comments#delete', as: 'delete'
      end
    end
    resources :school_years, only: [:new, :create]
    resources :companies, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :schools, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :users, only: [:new, :create, :show, :destroy, :index, :update]
    resources :school_semesters, only: [:new, :create, :show, :destroy, :index, :update], path: :semesters
    resources :school_class_types, only: [:new, :create, :show, :destroy, :index, :update] do
      post '/classes/command' => 'school_classes#command'

      resources :classes, only: [:new, :create, :show, :destroy, :index, :update], controller: :school_classes
    end

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy', as: :logout

    resource :dialogs do
      get '/invoice', to: 'dialogs#invoice'
      post '/invoice', to: 'dialogs#create_invoice'

      # get '/export'
      # post '/export', to: 'dialogs#export'

    end

    get '/dashboard', to: 'dashboard#show'
  end

  namespace :api do
    namespace :v1 do
      resources :school_classes, only: [:index], :defaults => {:format => 'json'}
      resources :schools, only: [:show], :defaults => {:format => 'json'}
      resources :companies, only: [:show], :defaults => {:format => 'json'}
      resources :pupils, only: [:update], :defaults => {:format => 'json'}
    end
  end

end

app/models/pupil_comment.rb
class PupilComment < ApplicationRecord
  belongs_to :user
  belongs_to :pupil, counter_cache: :comments_count

  validates_presence_of :text
end

app/controllers/admin/pupil_comments_controller.rb
class Admin::PupilCommentsController < AdminController

  def index
    @pupil = Pupil.find(params[:pupil_id])
    @pupil_comment = PupilComment.new
  end

  def create
    @pupil = Pupil.find(params[:pupil_id])
    @pupil_comment = PupilComment.new({
                                          pupil: @pupil,
                                          user: current_user})

    @pupil_comment.assign_attributes params.require(:comment).permit(:text)
    if @pupil_comment.save
      redirect_to admin_pupil_comments_path @pupil.id
    else
      flash.now[:error] = @pupil_comment.errors.full_messages.first

      render :index
    end

  end

  def delete
    @pupil = Pupil.find(params[:pupil_id])
    @pupil_comment = @pupil.comments.find(params[:comment_id])

    @pupil_comment.destroy

    redirect_to admin_pupil_comments_path @pupil.id
  end

  def update
    @pupil = Pupil.find(params[:pupil_id])
    @pupil_comment = @pupil.comments.find(params[:id])

    @pupil_comment.assign_attributes params.require(:comment).permit(:text)

    if @pupil_comment.save
      redirect_to admin_pupil_comments_path @pupil.id
    else
      flash.now[:error] = @pupil_comment.errors.full_messages.first

      render :index
    end
  end

end

app/views/admin/pupil_comments/index.html.erb
<%= form_for [:admin, @pupil, @pupil_comment], as: :comment, html: { class: 'comment-form' }, url: admin_pupil_comments_path(@pupil.id), method: :post, builder: BootstrapFormBuilder do |f| %>
  <div class="form-row">
    <%= f.form_group :text, "#{current_user.username}", col: 12 do %>
      <%= f.text_area :text, autofocus: true, rows: 4 %>
    <% end %>
  </div>
  <div class="text-right">
    <%= f.submit 'Speichern', class: 'btn btn-info' %>
  </div>
<% end %>
<% @pupil.comments.order(created_at: :DESC).each do |comment| %>
  <%= form_for comment, url: admin_pupil_comment_path(@pupil.id, comment.id), html: { class: 'comment-form', data: { controller: 'comment' } }, as: :comment, method: :PUT, builder: BootstrapFormBuilder do |f| %>
    <div class="form-row">
      <%= f.form_group :text, "#{comment.try(:created_at).try(:strftime, '%d.%m.%Y')} von #{comment.user ? comment.user.username : 'Unbekannt'}", col: 12 do %>
        <%= f.text_area :text, readonly: true, data: { target: 'comment.text' }, rows: 4 %>
        <div class="comment-form__buttons text-right">
          <button class="btn btn-xs btn-link" data-action="comment#edit">
            <%= fa_icon 'edit' %>
          </button>
          <%= link_to admin_pupil_comment_delete_path(@pupil.id, comment.id), class: 'btn btn-xs btn-link' do %>
            <%= fa_icon 'trash' %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>