config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root :controller => :register, :action => :index

  get '/register/success', to: 'register#success'
  get '/register/:step', to: 'register#show'
  post '/register/:step', to: 'register#create', as: 'register_step'

  get '/register', to: redirect('/register/1')

  resources :registrations, only: [:show, :index, :create]

  namespace :admin do
    root to: redirect('/admin/pupils?semester=current')
    post '/pupils/command' => 'pupils#command'
    post '/companies/command' => 'companies#command'
    post '/schools/command' => 'schools#command'
    post '/semesters/command' => 'school_semesters#command'
    post '/school_class_types/command' => 'school_class_types#command'
    post '/users/command' => 'users#command'
    resource :charts do
      get 'weekly'
    end

    resources :pupils, only: [:new, :create, :show, :destroy, :index, :update] do
      get :checkin, path: 'checkin', to: 'pupils#checkin'
      post :checkin, path: 'checkin', to: 'pupils#do_checkin'
      get :delete_photo, path: 'delete_photo', to: 'pupils#delete_photo'
      get :invoice, path: 'invoice', to: 'pupils#invoice'
      resources :comments, controller: 'pupil_comments' do
        get :delete, to: 'pupil_comments#delete', as: 'delete'
      end
    end
    resources :school_years, only: [:new, :create]
    resources :companies, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :schools, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :users, only: [:new, :create, :show, :destroy, :index, :update]
    resources :school_semesters, only: [:new, :create, :show, :destroy, :index, :update], path: :semesters
    resources :school_class_types, only: [:new, :create, :show, :destroy, :index, :update] do
      post '/classes/command' => 'school_classes#command'

      resources :classes, only: [:new, :create, :show, :destroy, :index, :update], controller: :school_classes
    end

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy', as: :logout

    resource :dialogs do
      get '/invoice', to: 'dialogs#invoice'
      post '/invoice', to: 'dialogs#create_invoice'

      # get '/export'
      # post '/export', to: 'dialogs#export'

    end

    get '/dashboard', to: 'dashboard#show'
  end

  namespace :api do
    namespace :v1 do
      resources :school_classes, only: [:index], :defaults => {:format => 'json'}
      resources :schools, only: [:show], :defaults => {:format => 'json'}
      resources :companies, only: [:show], :defaults => {:format => 'json'}
      resources :pupils, only: [:update], :defaults => {:format => 'json'}
    end
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::OrganisationsController
  def show
    @pupils = Pupil.limit(10).order(created_at: :desc)
    @comments = PupilComment.where("pupil_id IS NOT NULL").includes(:pupil, :user).order(created_at: :desc).limit(5)
  end
end

app/views/admin/dashboard/show.html.erb
<div class="row pt-4">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Letzte Kommentare</h5>
        <div>
          <% @comments.each do |comment| %>
            <div class="mb-3">
              <% if comment.pupil %>
                <div>
                  <%= link_to admin_pupil_path(comment.pupil) + "#comments" do %>
                    <%= comment.pupil.firstname %>
                    <%= comment.pupil.lastname %>
                  <% end %>
                </div>
              <% end %>
              <blockquote class="blockquote">
                <p class="mb-0"><%= comment.text %></p>
                <footer class="blockquote-footer">
                  von <%= comment.user.username %> am <span><%= l(comment.created_at) %></span>
                </footer>
              </blockquote>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Neueste Anmeldungen</h5>
        <div>
          <table class="table">
            <tbody>
            <% @pupils.each do |pupil| %>
              <tr>
                <td class="pl-0">
                  <%= l(pupil.created_at, format: "%d.%m.%y %H:%M Uhr") %>
                </td>
                <td>
                  <%= link_to admin_pupil_path(pupil) + "#dorm" do %>
                    <%= pupil.firstname %>
                    <%= pupil.lastname %>
                  <% end %>
                </td>
                <td>
                  <%= info_icon true, {title: pupil.age < 18 ? 'Minderjährig' : 'Volljährig'} do %>
                    <strong><%= pupil.age < 18 ? "M" : "V" %></strong>
                  <% end %>
                </td>
                <td>
                  <%= pupil.school_class_info %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-4">
    <iframe src="<%= weekly_admin_charts_path %>" frameborder="0" width="100%"></iframe>
  </div>
</div>