config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root :controller => :register, :action => :index

  get '/register/success', to: 'register#success'
  get '/register/:step', to: 'register#show'
  post '/register/:step', to: 'register#create', as: 'register_step'

  get '/register', to: redirect('/register/1')

  resources :registrations, only: [:show, :index, :create]

  namespace :admin do
    root to: redirect('/admin/pupils?semester=current')
    post '/pupils/command' => 'pupils#command'
    post '/companies/command' => 'companies#command'
    post '/schools/command' => 'schools#command'
    post '/semesters/command' => 'school_semesters#command'
    post '/school_class_types/command' => 'school_class_types#command'
    post '/users/command' => 'users#command'
    resource :charts do
      get 'weekly'
    end

    resources :pupils, only: [:new, :create, :show, :destroy, :index, :update] do
      get :checkin, path: 'checkin', to: 'pupils#checkin'
      post :checkin, path: 'checkin', to: 'pupils#do_checkin'
      get :delete_photo, path: 'delete_photo', to: 'pupils#delete_photo'
      get :invoice, path: 'invoice', to: 'pupils#invoice'
      resources :comments, controller: 'pupil_comments' do
        get :delete, to: 'pupil_comments#delete', as: 'delete'
      end
    end
    resources :school_years, only: [:new, :create]
    resources :companies, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :schools, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :users, only: [:new, :create, :show, :destroy, :index, :update]
    resources :school_semesters, only: [:new, :create, :show, :destroy, :index, :update], path: :semesters
    resources :school_class_types, only: [:new, :create, :show, :destroy, :index, :update] do
      post '/classes/command' => 'school_classes#command'

      resources :classes, only: [:new, :create, :show, :destroy, :index, :update], controller: :school_classes
    end

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy', as: :logout

    resource :dialogs do
      get '/invoice', to: 'dialogs#invoice'
      post '/invoice', to: 'dialogs#create_invoice'

      # get '/export'
      # post '/export', to: 'dialogs#export'

    end

    get '/dashboard', to: 'dashboard#show'
  end

  namespace :api do
    namespace :v1 do
      resources :school_classes, only: [:index], :defaults => {:format => 'json'}
      resources :schools, only: [:show], :defaults => {:format => 'json'}
      resources :companies, only: [:show], :defaults => {:format => 'json'}
      resources :pupils, only: [:update], :defaults => {:format => 'json'}
    end
  end

end

app/models/pupil.rb
class Pupil < ApplicationRecord
  MEASLES_VACCINATION_OPTIONS = %w(vaccinated certificated not_possible none)

  include AddressAttributes

  strip_attributes only: [:firstname, :lastname]

  attr_accessor :school_class_type_id

  attr_accessor :create_school
  attr_accessor :create_company

  attr_accessor :new_school
  attr_accessor :new_company
  attr_accessor :school_semester_id

  has_one :address, as: :addressable
  has_one :deposit
  has_one :car, class_name: 'PupilCar'
  has_one :wifi, class_name: 'PupilWifi'

  has_many :parents, class_name: 'PupilParent'
  has_many :comments, class_name: 'PupilComment'

  belongs_to :company, optional: true
  belongs_to :school, optional: true
  belongs_to :school_class, optional: true
  belongs_to :county

  has_one :school_class_type, through: :school_class, :source => 'type'
  has_one :school_semester, through: :school_class, :source => 'semester'
  has_one :covid_info

  has_many :comments, class_name: 'PupilComment'
  has_many :bills, class_name: 'PupilBill'

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :birthplace, presence: true
  validates :birthdate, presence: true
  validates :county_id, presence: true
  validates :nationality, presence: true
  validates :address, presence: true
  validates :arrival_day, presence: true

  validates_presence_of :measles_vaccination, on: :create
  validates_inclusion_of :measles_vaccination, in: Pupil::MEASLES_VACCINATION_OPTIONS + [nil]
  validates_associated :covid_info, on: :create

  validate :parents_under_age

  validates_associated :address
  validates_associated :parents

  validates_associated :new_company, if: -> {create_company == '1'}
  validates_associated :new_school, if: -> {create_school == '1'}

  accepts_nested_attributes_for :parents, :allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :bills, :allow_destroy => true

  accepts_nested_attributes_for :car, :allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :wifi, :allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :deposit, :allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :covid_info, :allow_destroy => true

  has_attached_file :photo, styles: {medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  scope :with_details, -> {includes(:school_class_type, :school_semester, :deposit, :car, :wifi)}

  before_save :save_new_organisations

  def school_class_type_id
    return @school_class_type_id if @school_class_type_id
    if school_class
      school_class.type.id
    end
  end

  def school_class_type_id=(id)
    @school_class_type_id = id
  end

  def male
    ret = super
    ret == nil ? false : ret
  end

  def fullname
    "#{firstname} #{lastname}"
  end

  def school_class_info
    school_class_type ? "#{school_class.short_name}" : ''
  end

  def deposit_info
    deposit ? "#{deposit.block} / #{deposit.nr}" : ''
  end

  def deposit_paid_in
    deposit && deposit.paid_in
  end

  def deposit_paid_out
    deposit && deposit.paid_out
  end

  def age
    birthdate ? ((Time.zone.now - birthdate.to_time) / 1.year.seconds).floor : 0
  end

  def minor?
    age < 18
  end

  def deposit_attributes=(attrs)
    assign_model_attributes(:deposit, attrs)
  end

  def wifi_attributes=(attrs)
    assign_model_attributes(:wifi, attrs)
  end

  def car_attributes=(attrs)
    assign_model_attributes(:car, attrs)
  end

  def covid_info_attributes=(attrs)
    assign_model_attributes(:covid_info, attrs)
  end

  def bills_attributes=(attrs)
    update_bills = []
    attrs.each do |index, b|
      if b['value'].present?
        bill = self.bills.find_or_create_by(cw: b['cw'])
        bill.assign_attributes(b)
        update_bills << bill
      else
        bill = self.bills.where(cw: b['cw']).first
        if bill
          bill.mark_for_destruction
          update_bills << bill
        end
      end
    end
    self.bills = update_bills
  end

  def parents_attributes=(parents_attrs)
    update_parents = []
    parents_attrs.each {|_, parent|
      unless parent['_destroy'] == '1'
        if parent['id'].present?
          p = self.parents.where(id: parent['id']).first
          if p
            p.assign_attributes(parent.except('id', '_destroy'))
            update_parents << p
          end
        else
          p = self.parents.build(parent.except('_destroy'))
          if p.attributes.any? do |_, value|
            value.present?
          end
            update_parents << p
          end
        end
      end
    }
    if minor? && update_parents.empty?
      update_parents << self.parents.first if self.parents.any?
    end
    self.parents = update_parents
  end

  def new_school=(attr)
    @new_school = School.new(attr)
  end

  def new_school
    @new_school || School.new
  end

  def new_company=(attr)
    @new_company = Company.new(attr)
  end

  def new_company
    @new_company || Company.new
  end

  def public_id
    Base64.encode64("#{firstname}|#{lastname}|#{passwd}").gsub("\n", "!")
  end

  def school_semester_id=(id)
    @school_semester_id = id
    unless id&.blank?
      semester = SchoolSemester.find(id)
      if semester && school_class_type_id
        self.school_class = SchoolClass.find_or_create_by(start_semester: semester.id, school_class_type_id: school_class_type_id)
      end
    end
  end

  def school_semester_id
    return @school_semester_id if @school_semester_id
    if school_class&.start_semester
      school_class.start_semester.id
    end
  end

  def self.find_by_public_id(public_id)
    decoded = Base64.decode64(public_id.gsub('!', '\n'))
    splitted = decoded.split('|')

    self.where("lower(firstname) = ? AND lower(lastname) = ? AND passwd = ?", splitted[0].downcase, splitted[1].downcase, splitted[2].upcase).first
  end

  private

  def assign_model_attributes(relation, attrs)
    is_blank = attrs.all? {|_, value| value.blank?}
    model = self.send(relation)
    if is_blank
      model.destroy if model
    elsif model
      model.assign_attributes(attrs)
    else
      self.send("build_#{relation}", attrs)
    end
  end

  def save_new_organisations
    @new_company.save && self.company = @new_company if create_company == '1'
    @new_school.save && self.school = @new_school if create_school == '1'
    @new_school_class.save if @new_school_class
  end

  def parents_under_age
    errors.add(:parents, :blank) if parents.select {|p| p.valid?}.empty? && age < 18
  end

end

app/controllers/admin/pupils_controller.rb
class Admin::PupilsController < AdminController

  def new
    @pupil = Pupil.new

    load_data

    render :show
  end

  def create
    @pupil = Pupil.new

    @pupil.assign_attributes(pupil_params)

    if @pupil.save
      redirect_to(admin_pupil_url(@pupil), success: 'Schüler erfolgreich gespeichert.')
    else
      flash.now[:alert] = @pupil.errors.full_messages.first

      load_data

      render :show
    end
  end

  def update
    @pupil = Pupil.find(params[:id])

    @pupil.assign_attributes(pupil_params)

    if @pupil.save
      redirect_to(admin_pupil_url(@pupil), success: 'Schüler erfolgreich gespeichert.')
    else
      flash.now[:alert] = @pupil.errors.full_messages.first

      load_data

      render :show
    end

  end

  def delete_photo
    @pupil = Pupil.find(params[:pupil_id])

    @pupil.photo = nil

    @pupil.save

    redirect_to(admin_pupil_url(@pupil), success: 'Foto erfolgreich gelöscht.')
  end

  def edit
    @pupil = Pupil.find(params[:id])

    load_data
  end

  def show
    @pupil = Pupil.find(params[:id])

    load_data

    respond_to do |format|
      format.html
      format.pdf do
        filename = "#{@pupil.lastname}_#{@pupil.firstname}"
        disposition = 'inline'
        pdf = RegistrationPdf.new(@pupil)

        send_data pdf.render,
                  filename: filename,
                  type: 'application/pdf',
                  disposition: disposition
      end
    end
  end

  def index
    @pupils = Pupil.with_details.order(lastname: :ASC)
    @companies = Company.order(name: :ASC)

    if params[:semester] == 'current'
      @semester = SchoolSemester.latest
    elsif params[:semester].present?
      @semester = SchoolSemester.find(params[:semester])
    else
      @semester = nil
    end

    filters = params.permit(:cw, :search, :status, :deposit, :company, :school_class_type, :county)
    filters[:semester] = @semester

    @pupils = PupilFilter.filter(filters, @pupils)
    @companies = @companies.where(id: @pupils.map {|p| p.company_id})
    @semesters = SchoolSemester.order(start_date: :DESC).all

    @deposit_options = [
        ['Alle', :all],
        ['Noch nicht eingezahlt', :not_paid_in],
        ['Noch nicht ausgezahlt', :not_paid_out],
        ['Ausgezahlt', :paid_out]
    ]
  end


  def export(ids)
    xls = PupilListXLS.new(ids)

    send_data xls.render,
              filename: "Export_#{Date.today}.xlsx",
              type: 'application/excel',
              disposition: 'inline'
  end

  def load_data
    @companies = Company.with_address.order(name: :ASC).all
    @schools = School.with_address.order(name: :ASC).all
    @school_class_types = SchoolClassType.order(abbreviation: :ASC).all
    @counties = County.order(name: :ASC).all
    @school_classes = @pupil.school_class ? @pupil.school_class.type.school_classes.with_type_and_semester.all : []
  end

  def checkin
    @pupil = Pupil.find(params[:pupil_id])

  end


  private

  def pupil_params
    address_attributes = [:street, :city, :zipcode, :home_nr, :mobile_nr, :fax_nr]

    params
        .require(:pupil).permit(
        :firstname, :lastname,
        :male, :email, :photo,
        :splitted_custody,
        :arrival_day,
        {address_attributes: address_attributes},
        {deposit_attributes: [:block, :nr, :paid_in, :paid_out, :value]},
        {car_attributes: [:name, :sign, :color, :key]},
        {wifi_attributes: [:token1, :token2]},
        {parents_attributes: [:_destroy, :id, :phone_nr, :firstname, :lastname, {address_attributes: [:_destroy].concat(address_attributes)}]},
        {bills_attributes: [:cw, :value]},
        {covid_info_attributes: [:status, :first_vaccination_on, :second_vaccination_on, :tested_on, :last_vaccination_on]},
        :school_class_id,
        :company_id, :school_id,
        :create_company, {new_company: [:name, address_attributes: address_attributes]},
        :create_school, {new_school: [:name, address_attributes: address_attributes]},
        :birthplace, :birthdate,
        :nationality, :county_id,
        :measles_vaccination,
        :rent_on_account,
        :food_on_account,
        :checked_out,
        :permanent,
        :banished,
        :room,
        :min_to_arrive,
        :min_to_depart
    )
  end

end

app/controllers/api/v1/pupils_controller.rb
class Api::V1::PupilsController < ApplicationController
  include AuthenticationSystem
  before_action :login_required

  def update
    pupil = Pupil.find(params[:id])
    pupil.update(permitted_parameters)
  end

  def permitted_parameters
    params.permit(:room, :firstname, :lastname, :subclass)
  end
end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/views/admin/pupils/_billing.html.erb
<%
  time = Time.now
  current_year = Time.now.year
%>
<% oldest_bill = @pupil.bills.order(cw: :ASC).first %>
<% oldest_bill_time = oldest_bill ? Date.commercial(oldest_bill.year, oldest_bill.cweek).to_time : time %>
<% current_time = time - 30.weeks %>
<% current_time = current_time < oldest_bill_time ? current_time : oldest_bill_time %>
<% last_year = 0 %>
<% end_time = 32.weeks.from_now %>
<% index = 0 %>
<% begin %>
    <% current_year = current_time.year %>
    <% if current_year != last_year %>
        <% last_year = current_year %>
        <fieldset>
          <legend><%= current_year %></legend>
          <div class="row">
    <% end %>
    <div class="col-md-3">
      <div class="form-row mb-2">
        <label for="colFormLabelSm" class="col-4 col-form-label col-form-label-sm text-center">
          <%= current_time.strftime('%W') %>
        </label>
        <% cw = "#{current_year}-#{current_time.strftime('%W')}" %>
        <% bill = @pupil.bills.detect {|b| b.cw == cw} %>
        <div class="col-8">
          <input type="hidden" name="pupil[bills_attributes][<%= index %>][cw]" value="<%= cw %>">
          <input type="text" class="form-control form-control-sm" name="pupil[bills_attributes][<%= index %>][value]" value="<%= bill ? bill.value : "" %>">
        </div>
      </div>
    </div>
    <% current_time += 1.week %>
    <% index += 1 %>
    <% if current_time.year > current_year || current_time > end_time %>
        </div>
        </fieldset>
    <% end %>
<% end while current_time <= end_time %>

app/views/admin/pupils/_parent.html.erb
<% deletable = true if local_assigns[:deletable].nil? %>
<% is_new = false if local_assigns[:is_new].nil? %>
<% read_only = false if local_assigns[:read_only].nil? %>
<% deletable = deletable && !read_only %>

<div data-controller="parent" class="parent-form" style="<%= is_new ? 'display: none;' : '' %>">
  <%= parent_f.hidden_field :id %>
  <div class="form-row">
    <%= parent_f.form_group :firstname, 'Vorname', col: 3 do %>
        <%= read_only ? content_tag(:div, parent_f.object.firstname) : parent_f.text_field(:firstname) %>
    <% end %>
    <%= parent_f.form_group :lastname, 'Nachname', col: 3 do %>
        <%= read_only ? content_tag(:div, parent_f.object.lastname) : parent_f.text_field(:lastname) %>
    <% end %>
    <%= parent_f.form_group :phone_nr, 'Telefon-Nr.', col: 3 do %>
      <%= read_only ? content_tag(:div, parent_f.object.phone_nr) : parent_f.text_field(:phone_nr) %>
    <% end %>
    <% unless read_only %>
        <div class="form-group col-3 text-right">
          <label>
            &nbsp;
          </label>
          <% if deletable %>
              <div class="btn-group-toggle">
                <label class="btn btn-outline-danger btn-sm active">
                  <%= parent_f.check_box :_destroy, {data: {target: 'parent.destroy'}}, "1", nil %>
                  <%= fa_icon :trash %>
                  Entfernen
                </label>
              </div>
          <% end %>
        </div>
    <% else %>
        <% if !parent_f.object.address %>
            <%= parent_f.form_group :address, 'Adresse', col: 4 do %>
                <div>Gleiche Adresse wie oben</div>
            <% end %>
        <% end %>
    <% end %>
  </div>
  <div class="mb-2">
    <% unless read_only %>
        <%= parent_f.address_fields :address, parent_f.object.address || Address.new do |f| %>
            <%= f.check_box :_destroy, {checked: !parent_f.object.address, data: {target: 'parent.addressCheckbox', action: 'parent#toggleAddress'}}, "1", "0" %>
            <%= f.label :_destroy, 'Gleiche Adresse wie Azubi', class: 'form-check-label small' %>
        <% end %>
    <% end %>
  </div>
  <% unless read_only && !parent_f.object.address %>
      <div data-target="parent.address">
        <%= parent_f.address_fields :address, parent_f.object.address || Address.new do |f| %>
            <%= render partial: "partials/address_form", locals: {f: f, read_only: read_only, include_phone_nr: parent_f.object.persisted?} %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/admin/pupils/checkin.html.erb
<h2>
  <%= @pupil.fullname %>
  <% if @pupil.created_at %>
      <small class="muted-text">
        angemeldet am <%= @pupil.created_at.strftime("%d.%m.%Y %H:%M") %>
      </small>
  <% end %>
</h2>
<div class="row mt-4">
  <div class="col-12 col-md-9" data-controller="tab">
    <%= form_for @pupil, url: {action: "checkin"}, html: {class: "nifty_form"}, builder: BootstrapFormBuilder do |f| %>

        <div class="form-footer">
          <%= f.button "Abbrechen", {type: 'reset', class: 'btn btn-info'} %>
          <%= f.submit "Speichern", {class: 'btn btn-success'} %>
        </div>

    <% end %>
  </div>
  <div class="col-12 col-md-3">

  </div>
</div>

app/views/admin/pupils/create.html.erb
<h1>Pupils#create</h1>
<p>Find me in app/views/pupils/create.html.erb</p>

app/views/admin/pupils/destroy.html.erb
<h1>Pupils#destroy</h1>
<p>Find me in app/views/pupils/destroy.html.erb</p>

app/views/admin/pupils/index.html.erb
<% content_for :header do %>
  <div class="col-12">
    <%= link_to new_admin_pupil_path, class: 'btn btn-primary btn-sm' do %>
      <%= fa_icon :plus %>
      Neu
    <% end %>
    <button type="button" class="btn btn-danger btn-sm" data-controller="group-command" data-group-command="delete" data-command-confirm="Wollen Sie die ausgewählten Schüler wirklich löschen?">
      <%= fa_icon :trash %>
      Löschen
    </button>
    <% if current_user.is_admin? %>
      <button type="button" class="btn btn-success btn-sm" data-controller="invoice-dialog">
        <%= fa_icon :receipt %>
        Rechnung erstellen
      </button>
    <% end %>
    <% if current_user.is_admin? || current_user.can_export %>
      <button type="button" class="btn btn-info btn-sm" data-controller="group-command" data-group-command="export">
        <%= fa_icon "file-excel" %>
        Exportieren
      </button>
    <% end %>
  </div>
  <div class="col-12 col-md-8">
  </div>
<% end %>
<% content_for :content do %>
  <%= form_tag({controller: :pupils, action: :command}, method: :post, id: 'groupForm') do %>
    <%= hidden_field :command, :name, {value: 'delete'} %>

    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>
          <%= check_box(:command, :all, {}, 'all') %>
        </th>
        <th></th>
        <th scope="col">Name</th>
        <th>Information</th>
        <th class="text-center">Klasse</th>
        <th>Unterkl.</th>
        <th>Kaution</th>
        <th class="text-center">Zimmer</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @pupils.each do |pupil| %>
        <tr>
          <td>
            <%= check_box(:command, :ids, {:multiple => true}, pupil.id, false) %>
          </td>
          <td style="padding: 0; text-align: center;">
            <% if pupil.photo.exists? %>
                    <span class="pupil-avatar">
                      <%= image_tag pupil.photo.url(:thumb), height: "100%" %>
                    </span>
            <% end %>
          </td>
          <td>
            <%= pupil.lastname %>, <%= pupil.firstname %>
          </td>
          <td class="info-column">
            <%= info_icon true, {title: pupil.age < 18 ? 'Minderjährig' : 'Volljährig'} do %>
              <strong><%= pupil.age < 18 ? "M" : "V" %></strong>
            <% end %>
            <%= info_icon true, {title: pupil.male ? 'Männlich' : 'Weiblich'} do %>
              <%= pupil.male ? fa_icon("mars") : fa_icon("venus") %>
            <% end %>
            <%= info_icon pupil.wifi do %>
              <%= link_to admin_pupil_path(pupil) + "#dorm" do %>
                <%= fa_icon :wifi %>
              <% end %>
            <% end %>
            <%= info_icon pupil.car do %>
              <%= link_to admin_pupil_path(pupil) + "#dorm" do %>
                <%= fa_icon :car %>
              <% end %>
            <% end %>
            <%= info_icon pupil.rent_on_account, title: 'Miete auf Rechnung' do %>
              <strong>M</strong>
            <% end %>
            <%= info_icon pupil.food_on_account, title: pupil.food_on_account == 1 ? 'Halbpension' : pupil.food_on_account == 2 ? 'Vollpension' : false do %>
              <%= pupil.food_on_account == 1 ? 'HP' : pupil.food_on_account == 2 ? 'VP' : '–' %>
            <% end %>
            <%= info_icon pupil.splitted_custody > 0, title: 'Getrenntes Sorgerecht' do %>
              <strong>GS</strong>
            <% end %>
            <%= info_icon pupil.comments_count > 0, {} do %>
              <%= link_to admin_pupil_path(pupil) + "#comments", class: 'badge badge-info', data: {toggle: 'tooltip'}, title: "Kommentare" do %>
                <%= pupil.comments_count %>
              <% end %>
            <% end %>

          </td>
          <td class="text-center">
            <%= pupil.school_class_info %>
          </td>
          <td>
            <input type="text" value="<%= pupil.subclass %>" style="max-width: 80px; text-align: center; display: inline-block;" name="subclass" data-controller="pupil-edit" data-pupil-id="<%= pupil.id %>" class="form-control form-control-sm"/>
          </td>
          <td>
            <span data-toggle="tooltip" title="<%= "Eingezahlt: #{l pupil.deposit_paid_in}" if pupil.deposit_paid_in  %>"><%= pupil.deposit_info %></span>
            <% if pupil.deposit_paid_out %>
            <span data-toggle="tooltip" title="Ausgezahlt: <%= l pupil.deposit_paid_out %>">
              <%= fa_icon("check") %>
            </span>
            <% end %>
          </td>
          <td class="text-center">
            <input type="text" value="<%= pupil.room %>" style="max-width: 80px; text-align: center; display: inline-block;" name="room" data-controller="pupil-edit" data-pupil-id="<%= pupil.id %>" class="form-control form-control-sm"/>
          </td>
          <td>
            <%= link_to(admin_pupil_path(pupil) + '#personal', {class: 'btn btn-sm btn-primary', data: {toggle: 'tooltip'}, title: "Bearbeiten"}) do %>
              <%= fa_icon("edit") %>
            <% end %>
            <%= link_to(admin_pupil_path(pupil) + "#dorm", {class: 'btn btn-sm btn-outline-secondary', data: {toggle: 'tooltip'}, title: "An-/Abmeldung"}) do %>
              <%= fa_icon("sign-in-alt") %>
            <% end %>
            <%= link_to(pupil_download_path(pupil), {class: 'btn btn-sm btn-outline-info'}) do %>
              <%= fa_icon :print %>
            <% end %>
            <!--Anmelden-->
            <!--Abmelden-->
            <!--Kommentieren-->
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>
<%= content_for :footer do %>
  <%= @pupils.count %> insgesamt,
  <%= @pupils.where(male: false).count %> weiblich,
  <%= @pupils.where(male: true).count %> männlich
<% end %>
<div class="row">
  <div class="col-10">
    <%= render 'list_page' %>
  </div>
  <div class="col-2 bg-light position-fixed" style="right: 0;
      bottom: 0;
      top: 55px;
      padding-top: 20px;
      border-left: 1px solid lavender;">
    <%= form_tag({controller: :pupils}, method: 'get', enforce_utf8: false) do %>
      <div>
        <div class="form-group">
          <label for="search" class="small">Suche</label>
          <input id="search" name="search" type="text" value="<%= params[:search] %>" class="form-control form-control-sm"/>
        </div>
        <div class="form-group">
          <label for="semester" class="small">Semester</label>
          <select id="semester" name="semester" onchange="this.form.submit();" class="custom-select custom-select-sm">
            <%= options_for_select([['Alle Semester', ""]].concat(@semesters.map { |sem| [sem.name, sem.id] }), @semester ? @semester.id : 0) %>
          </select>
        </div>
        <div class="form-group">
          <label for="calendarweek" class="small">Kalenderwoche</label>
          <select id="calendarweek" name="cw" onchange="this.form.submit();" class="custom-select custom-select-sm">
            <%= options_for_select([['Alle Kalenderwochen', ""]].concat(calendar_weeks.map { |cw| ["KW #{cw} #{cw == current_cw ? ' - aktuell' : ''}", cw] }), params[:cw] || 0) %>
          </select>
        </div>
        <div class="form-group">
          <label for="status" class="small">Status</label>
          <select id="status" name="status" onchange="this.form.submit();" class="custom-select custom-select-sm">
            <%= options_for_select([['Alle', ""]].concat([["Angemeldet", :checked_in], ["Abgemeldet", :checked_out]]), params[:status] || "") %>
          </select>
        </div>
        <div class="form-group">
          <label for="deposit" class="small">Kaution</label>
          <select id="deposit" name="deposit" onchange="this.form.submit();" class="custom-select custom-select-sm">
            <%= options_for_select(@deposit_options, params[:deposit] || :all) %>
          </select>
        </div>
        <div class="form-group">
          <label for="company" class="small">Firma</label>
          <select id="company" name="company" onchange="this.form.submit();" class="custom-select custom-select-sm">
            <%= options_for_select([['Alle Firmen', ""]].concat(@companies.map { |com| [com.name, com.id] }), params[:company] || 0) %>
          </select>
        </div>
        <div class="form-group">
          <label for="school_class_type" class="small">Ausbildungsrichtung</label>
          <%= select_tag :school_class_type,
                         options_for_select([['Alle', ""]].concat(SchoolClassType.where("name > ''").order(name: :ASC).all.map {|sc|["#{sc.name} (#{sc.abbreviation.strip})", sc.id]}), params[:school_class_type]),
                         {class: "custom-select custom-select-sm", onchange: "this.form.submit();" }  %>
        </div>
        <div class="form-group">
          <label for="school_class_type" class="small">Landkreis</label>
          <%= select_tag :county,
                         options_for_select([['Alle', ""]].concat(County.where("name > ''").order(name: :ASC).all.map { |c| ["#{c.name}", c.id] }), params[:county]),
                         {class: "custom-select custom-select-sm", onchange: "this.form.submit();"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/pupils/update.html.erb
<h1>Pupils#update</h1>
<p>Find me in app/views/pupils/update.html.erb</p>