config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root :controller => :register, :action => :index

  get '/register/success', to: 'register#success'
  get '/register/:step', to: 'register#show'
  post '/register/:step', to: 'register#create', as: 'register_step'

  get '/register', to: redirect('/register/1')

  resources :registrations, only: [:show, :index, :create]

  namespace :admin do
    root to: redirect('/admin/pupils?semester=current')
    post '/pupils/command' => 'pupils#command'
    post '/companies/command' => 'companies#command'
    post '/schools/command' => 'schools#command'
    post '/semesters/command' => 'school_semesters#command'
    post '/school_class_types/command' => 'school_class_types#command'
    post '/users/command' => 'users#command'
    resource :charts do
      get 'weekly'
    end

    resources :pupils, only: [:new, :create, :show, :destroy, :index, :update] do
      get :checkin, path: 'checkin', to: 'pupils#checkin'
      post :checkin, path: 'checkin', to: 'pupils#do_checkin'
      get :delete_photo, path: 'delete_photo', to: 'pupils#delete_photo'
      get :invoice, path: 'invoice', to: 'pupils#invoice'
      resources :comments, controller: 'pupil_comments' do
        get :delete, to: 'pupil_comments#delete', as: 'delete'
      end
    end
    resources :school_years, only: [:new, :create]
    resources :companies, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :schools, only: [:new, :create, :show, :destroy, :index, :update] do
      resources :comments, controller: 'comments' do
        get :delete, to: 'comments#delete', as: 'delete'
      end
    end
    resources :users, only: [:new, :create, :show, :destroy, :index, :update]
    resources :school_semesters, only: [:new, :create, :show, :destroy, :index, :update], path: :semesters
    resources :school_class_types, only: [:new, :create, :show, :destroy, :index, :update] do
      post '/classes/command' => 'school_classes#command'

      resources :classes, only: [:new, :create, :show, :destroy, :index, :update], controller: :school_classes
    end

    get '/login', to: 'sessions#new', as: :login
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy', as: :logout

    resource :dialogs do
      get '/invoice', to: 'dialogs#invoice'
      post '/invoice', to: 'dialogs#create_invoice'

      # get '/export'
      # post '/export', to: 'dialogs#export'

    end

    get '/dashboard', to: 'dashboard#show'
  end

  namespace :api do
    namespace :v1 do
      resources :school_classes, only: [:index], :defaults => {:format => 'json'}
      resources :schools, only: [:show], :defaults => {:format => 'json'}
      resources :companies, only: [:show], :defaults => {:format => 'json'}
      resources :pupils, only: [:update], :defaults => {:format => 'json'}
    end
  end

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  layout 'register'

  def index

    redirect_to register_path(1)
  end

  def show
    @step = params[:step].to_i

    completed_step

    pupil

    load_data

    if @step > completed_step + 1
      redirect_to register_step_path(completed_step + 1)
    else
      render :show
    end

  end

  def create
    @step = params[:step].to_i

    pupil

    if validate_step(@step)
      session[:completed_step] = @step
      if @step < 5
        redirect_to register_step_path(@step + 1)
      else
        session[:completed_step] = nil
        session[:register] = nil
        redirect_to register_success_path(id: @pupil.public_id)
      end
    else
      session[:completed_step] = @step - 1
      load_data
      # flash[:danger] = 'Fehler beim Ausfüllen. Bitte überprüfe die rotmarkierten Felder!'
      render :show
    end
  end

  def success
    public_id = params[:id]
    @pupil = Pupil.find_by_public_id(public_id)

    if @pupil

    else
      redirect_to register_path
    end


  end

  private

  def completed_step
    session[:completed_step] ||= 0
  end

  def validate_step step
    address_attributes = [:_destroy, :street, :zipcode, :city, :home_nr, :fax_nr, :mobile_nr]
    case step
      when 1
        permit_params(:firstname, :lastname, :birthplace, :male, :birthdate, :nationality, :county_id, address_attributes: address_attributes)
      when 2
        permit_params(:splitted_custody, parents_attributes: [:_destroy, :firstname, :lastname, :phone_nr, address_attributes: address_attributes])
      when 3
        permit_params(:company_id, :school_id, :school_class_type_id, :school_semester_id, :subclass, :create_company, {new_company: [:name, address_attributes: address_attributes]}, :create_school, {new_school: [:name, address_attributes: address_attributes]})
      when 4
        permit_params(
          :arrival_day,
          :permanent,
          :min_to_arrive,
          :min_to_depart,
          :information,
          :measles_vaccination,
          { covid_info_attributes: [:status, :first_vaccination_on, :second_vaccination_on, :tested_on, :last_vaccination_on] }
        )
      when 5
        @pupil = pupil
        @pupil.passwd = (0...6).map {(65 + rand(26)).chr}.join
        @pupil.save
      else
        false
    end
  end

  def pupil
    @pupil = Pupil.new
    session_steps.each do |key, value|
      @pupil.assign_attributes(value)
    end
    @pupil
  end

  def permit_params(*args)
    @pupil = pupil
    pupil_params = params.require(:pupil).permit(*args)
    @pupil.assign_attributes(pupil_params)
    @pupil.validate
    error_index = args.index do |attribute_name|
      key = attribute_name
      if attribute_name.is_a? Hash
        key = attribute_name.keys.first.to_s.gsub('_attributes', '').to_sym
      end
      # key = key.to_s.gsub('_id', '').to_sym
      @pupil.errors.messages[key].any?
    end
    session_steps[@step] = pupil_params

    error_index == nil ? true : false
  end

  def session_steps
    session[:register] ||= {}
  end

  def load_data
    @companies = Company.with_address.order(name: :ASC).all
    @schools = School.with_address.order(name: :ASC).all
    @school_class_types = SchoolClassType.order(abbreviation: :ASC).all
    @school_semesters = SchoolSemester.where("start_date >= ?", 3.years.ago).order(start_date: :DESC).all
    @counties = County.order(name: :ASC).all
  end


end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/register/_step1.html.erb
<fieldset>
  <legend>Persönliche Daten</legend>
  <div class="form-row">
    <%= f.form_group :firstname, 'Vorname', col: 3 do %>
        <%= f.text_field :firstname %>
    <% end %>
    <%= f.form_group :lastname, 'Nachname', col: 5 do %>
        <%= f.text_field :lastname %>
    <% end %>
    <%= f.form_group :male, 'Geschlecht', col: 4 do %>
        <div class="btn-group btn-group-toggle btn-block" data-toggle="buttons">
          <label class="btn btn-sm btn-secondary">
            <%= f.radio_button "male", false, class: 'form-check-input' %>
            Weiblich
          </label>
          <label class="btn btn-sm btn-secondary">
            <%= f.radio_button "male", true, class: 'form-check-input' %>
            Männlich
          </label>
        </div>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :birthplace, 'Geburtsort', col: 8 do %>
        <%= f.text_field :birthplace %>
    <% end %>
    <%= f.form_group :birthdate, 'Geburtstag', col: 4 do %>
        <%= f.date_field :birthdate, {start_date: 16.years.ago} %>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :nationality, 'Nationalität', col: 6 do %>
        <%= f.select :nationality, I18n.t('nationality').map {|k, n| [n, k]} %>
    <% end %>
  </div>
</fieldset>
<fieldset>
  <legend>Kontaktdetails des Auszubildenden (Wohnort und Telefon-Nr.)</legend>
  <div class="form-group">
    <%= f.fields_for :address, @pupil.address || @pupil.build_address do |f| %>
        <%= render partial: "partials/address_form", locals: {f: f} %>
    <% end %>
  </div>
  <div class="row">
    <%= f.form_group :county_id, 'Landkreis', col: 6 do %>
      <%= f.select :county_id, @counties.map {|county| [county.name, county.id]} %>
    <% end %>
  </div>
</fieldset>

app/views/register/_step2.html.erb
<fieldset>
  <legend>Kontaktdaten der Sorgeberechtigen <br/> bzw. Kontakpersonen bei volljährigen Azubis</legend>
  <div class="parent-list form-group" data-controller="parent-list">
    <%= f.fields_for :parents, @pupil.parents.any? ? @pupil.parents : @pupil.parents.build do |parent_f| %>
        <%= render partial: "admin/pupils/parent", locals: {parent_f: parent_f, deletable: parent_f.index > 0} %>
    <% end %>
    <%= f.fields_for 'new_parent', PupilParent.new, {} do |parent_f| %>
        <%= render partial: "admin/pupils/parent", locals: {parent_f: parent_f, deletable: true, is_new: true} %>
    <% end %>
    <a href="javascript: void 0;" data-action="parent-list#addParent">
      <%= fa_icon('plus') %>
      Weiteren Vertreter hinzufügen
    </a>
  </div>
  <div class="form-row">
    <%= f.form_group :splitted_custody, 'Sorgerecht', col: 12 do %>
        <div class="form-check">
          <%= f.radio_button :splitted_custody, '0', class: 'form-check-input' %>
          <%= f.label :splitted_custody_0, 'Gemeinsames Sorgerecht bei zusammenlebenden Sorgeberechtigten', class: 'form-check-label' %>
        </div>
        <div class="form-check">
          <%= f.radio_button :splitted_custody, '1', class: 'form-check-input' %>
          <%= f.label :splitted_custody_1, 'Gemeinsames Sorgerecht bei getrenntlebenden Sorgeberechtigten', class: 'form-check-label' %>
        </div>
        <div class="form-check">
          <%= f.radio_button :splitted_custody, '2', class: 'form-check-input' %>
          <%= f.label :splitted_custody_2, 'Alleiniges Sorgerecht des angegebenen Sorgeberechtigten', class: 'form-check-label' %>
        </div>
    <% end %>
  </div>
</fieldset>

app/views/register/_step3.html.erb
<fieldset>
  <legend>Ausbildungsklasse</legend>
  <div class="form-row">
    <%= f.form_group :school_class_type_id, 'Ausbilungsrichtung', col: 6 do %>
        <%= f.select :school_class_type_id, [['Auswählen', nil]].concat(@school_class_types.map {|sc| ["#{sc.abbreviation} - #{sc.name}", sc.id]}), {} %>
    <% end %>
    <%= f.form_group :school_semester_id, 'Ausbildungsbeginn', col: 3 do %>
        <%= f.select :school_semester_id, [['Auswählen', nil]].concat(@school_semesters.map {|se| [I18n.l(se.start_date, :format => '%B %Y'), se.id]}) %>
    <% end %>
    <%= f.form_group :subclass, 'Unterklasse', col: 3 do %>
        <%= f.text_field :subclass %>
    <% end %>
  </div>
</fieldset>
<%= render partial: 'partials/organisation_form', locals: {f: f, name: 'Firma', type: 'company', organisations: @companies} %>
<%= render partial: 'partials/organisation_form', locals: {f: f, name: 'Schule', type: 'school', organisations: @schools} %>

app/views/register/_step4.html.erb
<fieldset>
  <legend>An- und Abreise</legend>
  <div class="form-row">
    <%= f.form_group :arrival_day, 'Tag der Anreise', col: 4 do %>
        <%= f.date_field :arrival_day %>
    <% end %>
    <%= f.form_group :permanent, '', col: 6 do %>
        <div class="form-check">
          <%= f.check_box :permanent, class: 'form-check-input' %>
          <%= f.label :permanent, 'Dauerbeleger (jede Woche anwesend)', class: 'form-check-label small' %>
        </div>
    <% end %>
  </div>
  <p class="font-italic small">
    Bitte gib an, wie lange die <strong>Hin- und Rückfahrt</strong> mit öffentlichen Verkehrsmitteln dauern würde.
  </p>
  <div class="form-row">
    <%= f.form_group :min_to_arrive, 'Anreise in min.', col: 4 do %>
        <%= f.text_field :min_to_arrive, type: 'number' %>
    <% end %>
    <%= f.form_group :min_to_depart, 'Abreise in min.', col: 4 do %>
        <%= f.text_field :min_to_depart, type: 'number' %>
    <% end %>
  </div>
</fieldset>
<fieldset>
  <legend>Weitere wichtige Informationen</legend>
  <div class="form-row">
    <%= f.form_group :measles_vaccination, 'Angaben zum Masernschutzgesetz bitte auswählen:', col: 12 do %>
      <div class="form-check">
        <%= f.radio_button :measles_vaccination, :vaccinated, class: 'form-check-input' %>
        <%= f.label :measles_vaccination_vaccinated, class: 'form-check-label' %>
      </div>
      <div class="form-check">
        <%= f.radio_button :measles_vaccination, :certificated, class: 'form-check-input' %>
        <%= f.label :measles_vaccination_certificated, class: 'form-check-label' %>
      </div>
      <div class="form-check">
        <%= f.radio_button :measles_vaccination, :not_possible, class: 'form-check-input' %>
        <%= f.label :measles_vaccination_not_possible, class: 'form-check-label' %>
      </div>
      <div class="form-check">
        <%= f.radio_button :measles_vaccination, :none, class: 'form-check-input' %>
        <%= f.label :measles_vaccination_none, class: 'form-check-label' %>
      </div>
    <% end %>
  </div>
  <div class="form-row" data-controller="covid-form">
    <%= f.form_group :covid_info, 'Angaben zu COVID-19 bitte auswählen:', col: 12 do %>
      <%= f.fields_for(:covid_info, f.object.covid_info || CovidInfo.new) do |covid_f| %>
        <div class="form-row form-group">
          <div class="col-6">
            <%= covid_f.select :status, CovidInfo.status.values.map { |v| [v.text, v] }, {}, data: { "target": "covid-form.status" } %>
          </div>
        </div>
        <div class="form-row" data-target="covid-form.positive">
          <%= covid_f.form_group :tested_on, nil, col: 4, data: { target: "covid-form.tested" } do %>
            <%= covid_f.date_field :tested_on %>
          <% end %>
          <%= covid_f.form_group :first_vaccination_on, nil, col: 4 do %>
            <%= covid_f.date_field :first_vaccination_on %>
          <% end %>
          <%= covid_f.form_group :second_vaccination_on, nil, col: 4, data: { target: "covid-form.secondVaccination" } do %>
            <%= covid_f.date_field :second_vaccination_on %>
          <% end %>
          <%= covid_f.form_group :last_vaccination_on, nil, col: 4 do %>
            <%= covid_f.date_field :last_vaccination_on %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :information, 'Krankheiten, Medikamente oder andere für die Betreuung wichtige Informationen', col: 12 do %>
        <%= f.text_area :information, class: 'form-control', rows: 6 %>
    <% end %>
  </div>
</fieldset>

app/views/register/_step5.html.erb
<fieldset>
  <legend>Angaben zur Person</legend>
  <div class="form-row">
    <%= f.form_group :firstname, 'Vorname', col: 4 do %>
        <div class="input"><%= @pupil.firstname %></div>
    <% end %>
    <%= f.form_group :lastname, 'Nachname', col: 4 do %>
        <div class="input"><%= @pupil.lastname %></div>
    <% end %>
    <%= f.form_group :male, 'Geschlecht', col: 4 do %>
        <div class="input"><%= @pupil.male ? 'männlich' : 'weiblich' %></div>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :birthdate, 'Geburtstag', col: 4 do %>
        <div class="input"><%= I18n.localize(@pupil.birthdate) %></div>
    <% end %>
    <%= f.form_group :birthplace, 'Geburtsort', col: 4 do %>
        <div class="input"><%= @pupil.birthplace %></div>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :nationality, 'Nationalität', col: 4 do %>
        <div class="input"><%= I18n.t("nationality.#{@pupil.nationality}") %></div>
    <% end %>
    <%= f.form_group :county, 'Landkreis', col: 4 do %>
        <div class="input">
          <%= @pupil.county.name %> (<%= @pupil.county.state.name %>)
        </div>
    <% end %>
  </div>
</fieldset>
<fieldset>
  <legend>Adresse</legend>
  <%= f.fields_for :address do |address_f| %>
      <%= render partial: "partials/address_form", locals: {f: address_f, read_only: true} %>
  <% end %>
</fieldset>
<%= f.fields_for :parents do |parent_f| %>
    <fieldset>
      <legend>Gesetzlicher Vertreter</legend>
      <%= render partial: "admin/pupils/parent", locals: {parent_f: parent_f, read_only: true} %>
    </fieldset>
<% end %>
<fieldset>
  <legend>Internatsnutzung</legend>
  <div class="form-row">
    <%= f.form_group :school_class_type, 'Ausbildungsrichtung', col: 4 do %>
      <div class="input"><%= @pupil.school_class_type ? @pupil.school_class_type&.name : 'Keine' %></div>
    <% end %>
    <%= f.form_group :school_class_type, 'Ausbildungsbeginn', col: 4 do %>
      <div class="input"><%= @pupil.school_semester ? I18n.l(@pupil.school_semester&.start_date, :format => '%B %Y') : '-' %></div>
    <% end %>
    <%= f.form_group :school_class_type, 'Unterklasse', col: 3 do %>
      <div class="input"><%= @pupil.subclass || '-' %></div>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :arrival_day, 'Tag der Anreise', col: 3 do %>
        <div class="input"><%= I18n.localize(@pupil.arrival_day) %></div>
    <% end %>
    <%= f.form_group :permanent, 'Dauerbeleger', col: 2 do %>
        <div class="input"><%= @pupil.permanent ? 'JA' : 'NEIN' %></div>
    <% end %>
    <%= f.form_group :min_to_arrive, 'Dauer der Anreise', col: 3 do %>
        <div class="input"><%= @pupil.min_to_arrive %> Minuten</div>
    <% end %>
    <%= f.form_group :min_to_depart, 'Dauer der Abreise', col: 3 do %>
        <div class="input"><%= @pupil.min_to_depart %> Minuten</div>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :measles_vaccination, 'Angaben zum Masernschutzgesetz:', col: 12 do %>
      <div class="input"><%= I18n.t("activerecord.attributes.pupil.measles_vaccination_#{@pupil.measles_vaccination}") %></div>
    <% end %>
  </div>
  <div class="form-row">
    <%= f.form_group :covid_info, 'Angaben zu COVID-19:', col: 12 do %>
      <div class="row">
        <div class="col-md-4">
          <div class="input"><%= @pupil.covid_info.status.text %></div>
        </div>
        <div class="col-md-8">
          <% if @pupil.covid_info.status.vaccinated? %>
            Erstimpfung: <%= l(@pupil.covid_info.first_vaccination_on) %><br>
            Zweitimpfung: <%= @pupil.covid_info.second_vaccination_on && l(@pupil.covid_info.second_vaccination_on) %><br>
            Letzte Folgeimpfung: <%= @pupil.covid_info.last_vaccination_on && l(@pupil.covid_info.last_vaccination_on) %>
          <% elsif @pupil.covid_info.status.recovered? %>
            Testdatum: <%= l(@pupil.covid_info.tested_on) %><br>
            Erstimpfung: <%= @pupil.covid_info.first_vaccination_on && l(@pupil.covid_info.first_vaccination_on) %><br>
            Letzte Folgeimpfung: <%= @pupil.covid_info.last_vaccination_on && l(@pupil.covid_info.last_vaccination_on) %>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

</fieldset>

app/views/register/show.html.erb
<div class="bs-wizard mb-3 d-none d-md-flex" style="border-bottom:0;">
  <% ['Persönliche Daten', 'Gesetzliche Vertreter', 'Ausbildung', 'Internatsnutzung', 'Abschließen'].each_with_index do |name, index| %>
      <div class="bs-wizard-step <%= class_name({complete: (index < session[:completed_step] && (index + 1 < @step)), active: ((index + 1) == @step), disabled: (index >= @step)}) %>">
        <div class="text-center bs-wizard-stepnum"><%= name %></div>
        <div class="progress">
          <div class="progress-bar"></div>
        </div>
        <%= link_to('', register_step_path((index + 1).to_s), class: 'bs-wizard-dot')%>
      </div>
  <% end %>
</div>

<%= form_for @pupil, url: register_step_path(@step), builder: BootstrapFormBuilder do |f| %>
    <div class="form-header">

    </div>
    <div class="form-body">
      <%= render partial: "step#{@step}", locals: {f: f} %>
    </div>
    <div class="form-footer">
      <div>
        <%= link_to('Zurück', register_step_path(@step - 1), class: 'btn btn-secondary') if @step > 1 %>
        <input type="submit" value="<%= @step < 5 ? 'Weiter': 'Anmelden' %>" class="btn btn-primary"/>
      </div>
    </div>
<% end %>

app/views/register/success.html.erb
<div class="">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="mb-4 mt-4 text-center">
        <div class="text-success mb-3">
          <span class="rounded-circle success-circle">
            <%= fa_icon('check 3x') %>
          </span>
        </div>
        <h3>Du hast dich erfolgreich angemeldet!</h3>
      </div>
      <div class="form-body text-center">
        <p class="large mb-4">
          Bitte drucke deinen Anmeldebogen aus und gebe diesen <br/> mit <b>zwei</b> Passbildern versehen
          beim Internat ab.
        </p>
        <div class="text-center">
          <%= link_to(registration_path(@pupil.public_id, 'pdf'), class: 'btn btn-success mb-5') do %>
              <%= fa_icon(:download) %> Anmeldebogen herunterladen
          <% end %>
        </div>
        <p>
          Wenn du ihn später ausdrucken willst, notiere dir bitte folgenden Code: <b><?= $pw ?></b>
        </p>
        <div class="p-3 mb-3" style="background: white;">
          <h5 class="mb-0 text-center"><%= @pupil.passwd %></h5>
        </div>
        <p class="small">
          <b>Hinweis:</b> Wenn eine Unterbringung <b>nicht</b> möglich ist, informieren wir dich.
        </p>
      </div>
    </div>
  </div>

</div>